### ISSUE TITLE
Ran the command `yarn install` failed

### ISSUE THREAD

**Issue by joint-song** [EdurtIO/incubator-dbm#8]
**Describe the bug**
Running `yarn install` at the root directory of workspace failed.

**To Reproduce**
1. Go to root directory.
2. Type `yarn insall` and return.
3. Terminal would report error with information:
4. See error:
```
Error: Unresolved node modules: highcharts
    at /~/incubator-dbm/node_modules/electron-builder-lib/src/util/packageDependencies.ts:109:19
From previous event:
    at Collector.resolveUnresolvedHoisted (/~/incubator-dbm/node_modules/electron-builder-lib/out/util/packageDependencies.js:206:11)
    at /~/incubator-dbm/node_modules/electron-builder-lib/src/util/packageDependencies.ts:85:18
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Collector.collect (/~/incubator-dbm/node_modules/electron-builder-lib/out/util/packageDependencies.js:154:11)
    at computeDependencies (/~/incubator-dbm/node_modules/electron-builder-lib/src/util/packageDependencies.ts:50:26)
    at /~/incubator-dbm/node_modules/electron-builder-lib/src/util/packageDependencies.ts:45:28
    at Generator.next (<anonymous>)
```

**Expected behavior**
yarn install all dependencies successfully.

**Screenshots**
No.

**Component (please set component name):**
 - Component: yarn
 - Version 1.17.3
 - Component: npm
 - Version 7.19.1
 - Component: node
 - Version v12.18.2

**Additional context**
`yarn -v`: *1.17.3*
`npm -v`: *7.19.1*
`node -v`: *v12.18.2*
The ***highcharts*** as a peerDependency is in package.json of `highchars-vue`. After installing highcharts by command `yarn add highcharts@latest`, errors were gone.

**Comment by qianmoQ** [comment]
Fix on [commit](https://github.com/EdurtIO/incubator-dbm/commit/81d4b9dac09d53a0a1ac37c78e4ae9cacbed1d11)
